services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: nextick-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms512M"
      KAFKA_LOG_RETENTION_HOURS: 2
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 29092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    stop_grace_period: 30s
    networks:
      - nextick_net
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: nextick-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: NexTick-Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - nextick_net
    depends_on:
      kafka:
        condition: service_healthy

  questdb:
    image: questdb/questdb:latest
    container_name: nextick-questdb
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
    networks:
      - nextick_net
    volumes:
      - ./data/questdb:/var/lib/questdb

  data-producer:
    build: .
    container_name: nextick-data-producer
    command: python -m data_pipeline.producer.binance_producer
    env_file:
      - data_pipeline/.env
    environment:
      - KAFKA_BROKER=kafka:29092
      - KAFKA_SERVER=kafka:29092
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - nextick_net
    depends_on:
      - kafka
    restart: unless-stopped

  data-processor:
    build: .
    container_name: nextick-data-processor
    command: >
      bash -c "
      echo 'Waiting for QuestDB to be ready...';
      while ! python -c 'import socket; socket.create_connection((\"questdb\", 8812))' 2>/dev/null; do
        sleep 2;
      done;
      echo 'QuestDB is ready! Starting Processor...';
      python -m data_pipeline.processor.candle_processor
      "
    env_file:
      - data_pipeline/.env
    environment:
      - KAFKA_BROKER=kafka:29092
      - KAFKA_SERVER=kafka:29092
      - QUESTDB_HOST=questdb
    networks:
      - nextick_net
    depends_on:
      - kafka
      - questdb
    restart: unless-stopped

networks:
  nextick_net:
    driver: bridge